notepad .github\workflows\python-app.yml

name: Python CI/CD

# Triggers the workflow on push or pull request events to the main branch
on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

# Define the jobs that will be executed in the workflow
jobs:
  build:
    # Define the environment for running the job (Ubuntu in this case)
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'  # Set the Python version (3.x for the latest)
    
    # Install dependencies from requirements.txt (or any other step you may have for dependencies)
    - name: Install dependencies
      run: |
        python -m venv venv  # Create a virtual environment
        source venv/bin/activate  # Activate the virtual environment (works on Linux/Ubuntu)
        pip install -r requirements.txt  # Install dependencies from requirements.txt
    
    # Run unit tests
    - name: Run tests
      run: |
        source venv/bin/activate  # Activate the virtual environment again
        python -m unittest discover tests  # Run the tests in the 'tests' folder
    
    # Upload test results (optional)
    - name: Upload test results (optional)
      uses: actions/upload-artifact@v2
      with:
        name: test-results  # Name for the uploaded artifact
        path: test-results/  # Path to the folder with test results
